from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AdicionarEventoGoogleView,
    AgendasCompartilhadasListView,
    AnexoListCreateView,
    AniversariantesDoDiaView,
    AtendimentoDetailView,
    AtendimentoListCreateView,
    BuscaGlobalView,
    CategoriaAtendimentoListView,
    CategoriaContatoListView,
    ContaListView,
    CriarEventoGoogleView,
    CustomPasswordResetView,
    CustomPasswordResetConfirmView,
    DashboardSummaryView,
    EditarExcluirEventoGoogleView,
    EspacoAgendaView,
    EspacoListCreateView,
    EspacoDetailView,
    ExportMunicipesExcelView,
    GerarPdfAgendasReportView,
    GerarPdfCheckinsView,
    GerarPdfGoogleAgendaView,
    GerarPdfAtendimentoDetailView,
    GerarPdfAtendimentosView,
    GerarPdfLembretesView,
    GoogleAuthCallbackView,
    GoogleAuthInitiateView,
    LembreteListCreateView,
    LembreteDetailView,
    ListarEventosGoogleView,
    MarcarNotificacaoComoLidaView,
    MesclarDuplicatasView,
    MunicipeCheckDuplicatesView,
    MunicipeDetailDataView,
    MunicipeDetailView,
    MunicipeListCreateView,
    MunicipeLookupView,
    MyTokenObtainPairView,
    NotificacaoListView,
    RegistroVisitaListCreateView,
    RegistroVisitaDetailView,
    RelatorioAtendimentosPorCategoriaView,
    RelatorioAtendimentosPorContaView,
    RelatorioAtendimentosPorStatusView,
    RemoverLinkGoogleView,
    ReservaEspacoListCreateView,
    ReservaEspacoDetailView,
    SharedGoogleAgendaView,
    SolicitacaoAgendaDetailView,
    SolicitacaoAgendaListCreateView,
    TramitacaoDetailView,
    TramitacaoListCreateView,
    UserListView,
)

urlpatterns = [
    # --- Autenticação e Senha ---
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset_api'),
    path('password_reset/confirm/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm_api'),

    # --- Munícipes ---
    path('municipes/', MunicipeListCreateView.as_view(), name='municipe-list-create'),
    path('municipes/lookup/', MunicipeLookupView.as_view(), name='municipe-lookup'),
    path('municipes/export/excel/', ExportMunicipesExcelView.as_view(), name='export-municipes-excel'),
    path('municipes/aniversariantes-do-dia/', AniversariantesDoDiaView.as_view(), name='municipes-aniversariantes-dia'),
    path('municipes/<int:pk>/', MunicipeDetailView.as_view(), name='municipe-detail'),
    path('municipes/<int:pk>/historico/', MunicipeDetailDataView.as_view(), name='municipe-historico'),
    path('municipes/check-duplicates/', MunicipeCheckDuplicatesView.as_view(), name='municipe-check-duplicates'),
    path('municipes/mesclar-duplicatas/', MesclarDuplicatasView.as_view(), name='municipe-mesclar-duplicatas'), 
    
    # --- Atendimentos e sub-recursos (tramitações, anexos) ---
    path('atendimentos/', AtendimentoListCreateView.as_view(), name='atendimento-list-create'),
    path('atendimentos/<int:pk>/', AtendimentoDetailView.as_view(), name='atendimento-detail'),
    path('atendimentos/<int:pk>/pdf/', GerarPdfAtendimentoDetailView.as_view(), name='atendimento-detalhe-pdf'),
    path('atendimentos/<int:atendimento_pk>/tramitacoes/', TramitacaoListCreateView.as_view(), name='atendimento-tramitacao-list-create'),
    path('atendimentos/<int:atendimento_pk>/anexos/', AnexoListCreateView.as_view(), name='atendimento-anexos-list-create'),
    path('tramitacoes/<int:pk>/', TramitacaoDetailView.as_view(), name='tramitacao-detail'),
    path('checkins/', RegistroVisitaListCreateView.as_view(), name='registro-visita-list-create'),
    path('checkins/<int:pk>/', RegistroVisitaDetailView.as_view(), name='registro-visita-detail'),

    # --- Agendas ---
    path('agendas/', SolicitacaoAgendaListCreateView.as_view(), name='agenda-list-create'),
    path('agendas/<int:pk>/', SolicitacaoAgendaDetailView.as_view(), name='agenda-detail'),
    path('agendas/<int:pk>/criar-evento-google/', CriarEventoGoogleView.as_view(), name='agenda-criar-evento-google'),
    path('agendas/<int:pk>/remover-link-google/', RemoverLinkGoogleView.as_view(), name='agenda-remover-link-google'),
    path('agendas-compartilhadas/', AgendasCompartilhadasListView.as_view(), name='shared-agendas-list'),
    path('agendas-compartilhadas/<int:conta_id>/', SharedGoogleAgendaView.as_view(), name='shared-google-agenda'),
    path('espacos/<int:espaco_id>/agenda/', EspacoAgendaView.as_view(), name='espaco-agenda-list'),
    path('espacos/', EspacoListCreateView.as_view(), name='espaco-list-create'),
    path('espacos/<int:pk>/', EspacoDetailView.as_view(), name='espaco-detail'),
    path('reservas-espaco/', ReservaEspacoListCreateView.as_view(), name='reserva-espaco-list-create'),
    path('reservas-espaco/<int:pk>/', ReservaEspacoDetailView.as_view(), name='reserva-espaco-detail'),

    # --- Relatórios e Dashboards ---
    path('relatorios/atendimentos-por-status/', RelatorioAtendimentosPorStatusView.as_view(), name='relatorio-atendimentos-por-status'),
    path('relatorios/atendimentos-por-conta/', RelatorioAtendimentosPorContaView.as_view(), name='relatorio-atendimentos-por-conta'),
    path('relatorios/atendimentos-por-categoria/', RelatorioAtendimentosPorCategoriaView.as_view(), name='relatorio-atendimentos-por-categoria'),
    path('relatorios/atendimentos/pdf/', GerarPdfAtendimentosView.as_view(), name='relatorio-atendimentos-pdf'),
    path('relatorios/checkins/pdf/', GerarPdfCheckinsView.as_view(), name='relatorio-checkins-pdf'),
    path('relatorios/agendas/pdf/', GerarPdfAgendasReportView.as_view(), name='relatorio-agendas-pdf'),
    path('dashboard/summary/', DashboardSummaryView.as_view(), name='dashboard-summary'),
    path('relatorios/google-agenda/pdf/', GerarPdfGoogleAgendaView.as_view(), name='relatorio-google-agenda-pdf'),

    # --- Listas Gerais e Utilitários ---
    path('usuarios/', UserListView.as_view(), name='usuario-list'),
    path('contas/', ContaListView.as_view(), name='conta-list'),
    path('categorias/', CategoriaAtendimentoListView.as_view(), name='categoria-list'),
    path('contatos/categorias/', CategoriaContatoListView.as_view(), name='categoriacontato-list'),
    path('notificacoes/', NotificacaoListView.as_view(), name='notificacao-list'),
    path('notificacoes/<int:pk>/marcar-lida/', MarcarNotificacaoComoLidaView.as_view(), name='notificacao-marcar-lida'),
    path('busca/', BuscaGlobalView.as_view(), name='busca-global'),

    # --- Lembretes ---
    path('lembretes/', LembreteListCreateView.as_view(), name='lembrete-list-create'),
    path('lembretes/<int:pk>/', LembreteDetailView.as_view(), name='lembrete-detail'),
    path('relatorios/lembretes/pdf/', GerarPdfLembretesView.as_view(), name='relatorio-lembretes-pdf'),

    # --- Integração Google ---
    path('google/auth/initiate/', GoogleAuthInitiateView.as_view(), name='google-auth-initiate'),
    path('google/auth/callback/', GoogleAuthCallbackView.as_view(), name='google-auth-callback'),
    path('google/calendar/events/', ListarEventosGoogleView.as_view(), name='google-calendar-list-events'),
    path('google/calendar/events/create/', AdicionarEventoGoogleView.as_view(), name='google-calendar-create-event'),
    path('google/calendar/events/<str:eventId>/', EditarExcluirEventoGoogleView.as_view(), name='google-calendar-detail-event'),
]