# Generated by Django 5.2.3 on 2025-08-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='arte_convite',
            field=models.ImageField(blank=True, help_text='Faça o upload da arte ou convite do evento', null=True, upload_to='eventos/artes/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='Local a definir', help_text='Endereço ou nome do espaço do evento', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='agendado', max_length=10),
        ),
    ]
