# Generated by Django 5.2.3 on 2025-08-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_arte_convite_evento_local_evento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Controla se o evento está ativo para check-in via QR Code.'),
        ),
    ]
