# Generated by Django 5.2.3 on 2025-08-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_conta_brasao_instituicao_conta_logo_conta_and_more'),
        ('eventos', '0003_evento_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='conta',
            field=models.ForeignKey(default=1, help_text='Conta à qual este evento pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='atendimentos.conta'),
            preserve_default=False,
        ),
    ]
