# Generated by Django 5.2.3 on 2025-08-11 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_conta_brasao_instituicao_conta_logo_conta_and_more'),
        ('eventos', '0004_evento_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('convidado', 'Convidado'), ('confirmado', 'Confirmado'), ('presente', 'Presente')], default='convidado', max_length=15)),
                ('data_checkin', models.DateTimeField(blank=True, null=True, verbose_name='Data do Check-in')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to='eventos.evento')),
                ('municipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites', to='atendimentos.municipe')),
            ],
            options={
                'verbose_name': 'Convidado',
                'verbose_name_plural': 'Convidados',
                'unique_together': {('evento', 'municipe')},
            },
        ),
    ]
