# Generated by Django 5.2.3 on 2025-08-11 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_conta_brasao_instituicao_conta_logo_conta_and_more'),
        ('eventos', '0005_convidado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('instituicao_orgao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição/Órgão')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentes', to='eventos.evento')),
                ('municipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencas', to='atendimentos.municipe')),
            ],
            options={
                'verbose_name': 'Lista de Presença',
                'verbose_name_plural': 'Listas de Presença',
                'unique_together': {('evento', 'municipe')},
            },
        ),
    ]
