# Generated by Django 5.2.3 on 2025-08-11 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_conta_brasao_instituicao_conta_logo_conta_and_more'),
        ('eventos', '0006_listapresenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do serviço ou material a ser verificado.', max_length=255)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='atendimentos.conta')),
            ],
            options={
                'verbose_name': 'Item Mestre de Checklist',
                'verbose_name_plural': 'Itens Mestres de Checklist',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_usado', models.BooleanField(default=False, verbose_name='Link de preenchimento já foi usado?')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio do Checklist')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Checklist do Evento',
                'verbose_name_plural': 'Checklists dos Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventoChecklistItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações/Dados')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('evento_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_status', to='eventos.eventochecklist')),
                ('item_mestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.checklistitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Status do Item de Checklist',
                'verbose_name_plural': 'Status dos Itens de Checklist',
                'unique_together': {('evento_checklist', 'item_mestre')},
            },
        ),
    ]
