# Generated by Django 5.2.3 on 2025-08-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_checklistitem_eventochecklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='eventochecklist',
            name='responsavel_nome',
        ),
        migrations.RemoveField(
            model_name='eventochecklistitemstatus',
            name='data_conclusao',
        ),
        migrations.AddField(
            model_name='eventochecklist',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável que preencheu'),
        ),
    ]
