# Generated by Django 5.2.3 on 2025-08-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_remove_checklistitem_conta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'permissions': [('pode_gerenciar_eventos', 'Pode gerenciar o módulo de eventos')]},
        ),
    ]
