# Generated by Django 5.2.3 on 2025-08-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_evento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='arte_convite',
        ),
        migrations.CreateModel(
            name='Comunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição (Corpo do E-mail)')),
                ('arte', models.ImageField(blank=True, help_text='Arte principal do comunicado (imagem)', null=True, upload_to='comunicacoes/artes/')),
                ('anexo', models.FileField(blank=True, help_text='Documento anexo (PDF, etc.)', null=True, upload_to='comunicacoes/anexos/')),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], default='criado', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Comunicação',
                'verbose_name_plural': 'Comunicações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
