# Generated by Django 5.2.3 on 2025-08-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_conta_brasao_instituicao_conta_logo_conta_and_more'),
        ('eventos', '0011_destinatario_logdeenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da lista de mailing (ex: Imprensa, Vereadores).', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(help_text='Conta à qual esta lista de mailing pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='mailing_lists', to='atendimentos.conta')),
                ('municipes', models.ManyToManyField(blank=True, help_text='Contatos incluídos nesta lista.', related_name='mailing_lists', to='atendimentos.municipe')),
            ],
            options={
                'verbose_name': 'Lista de Mailing',
                'verbose_name_plural': 'Listas de Mailing',
                'ordering': ['nome'],
                'unique_together': {('conta', 'nome')},
            },
        ),
    ]
