# Generated by Django 5.2.3 on 2025-08-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_mailinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convidado',
            options={'ordering': ['ordem'], 'verbose_name': 'Convidado', 'verbose_name_plural': 'Convidados'},
        ),
        migrations.AddField(
            model_name='convidado',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Campo para ordenação manual.'),
        ),
    ]
