# Generated by Django 5.2.3 on 2025-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_alter_convidado_options_convidado_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído'), ('standby', 'Stand-by')], default='agendado', max_length=10),
        ),
    ]
