# Generated by Django 5.2.3 on 2026-05-05 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0047_campanhalogenvio_email_real_enviado'),
        ('eventos', '0018_comunicacao_grupos_inclusao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSupressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='E-mail normalizado (lowercase) que deve ser suprimido.', max_length=254, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo (Bloqueado)'), ('liberado', 'Liberado')], db_index=True, default='ativo', help_text='Status da supressão.', max_length=10)),
                ('motivo', models.CharField(choices=[('bounce', 'Bounce (endereço inválido ou inexistente)'), ('invalid_syntax', 'Sintaxe inválida'), ('manual', 'Decisão manual'), ('outro', 'Outro')], default='bounce', help_text='Motivo da supressão.', max_length=20)),
                ('origem', models.CharField(choices=[('log_envio', 'Log de Envio (automático)'), ('usuario', 'Usuário (manual)'), ('import', 'Importação')], default='log_envio', help_text='Origem da supressão.', max_length=15)),
                ('primeira_ocorrencia', models.DateTimeField(auto_now_add=True, help_text='Data da primeira ocorrência/registro.')),
                ('ultima_ocorrencia', models.DateTimeField(auto_now=True, help_text='Data da última ocorrência/atualização.')),
                ('ocorrencias', models.PositiveIntegerField(default=1, help_text='Quantidade de ocorrências de erro para este e-mail.')),
                ('observacao', models.TextField(blank=True, default='', help_text='Observações adicionais sobre a supressão.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, help_text='Usuário que atualizou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supressoes_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('conta', models.ForeignKey(blank=True, help_text='Conta relacionada (opcional). Se nulo, supressão é global.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_suprimidos', to='atendimentos.conta')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que criou o registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supressoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supressão de E-mail',
                'verbose_name_plural': 'Supressões de E-mails',
                'ordering': ['-ultima_ocorrencia'],
                'indexes': [models.Index(fields=['email', 'status'], name='eventos_ema_email_6d5c97_idx'), models.Index(fields=['status', 'motivo'], name='eventos_ema_status_9c8258_idx')],
            },
        ),
    ]
