# Generated by Django 5.2.3 on 2025-07-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='google_calendar_id',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='ID (email) do Google Calendar para Visualização'),
        ),
    ]
