# Generated by Django 5.2.3 on 2025-07-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_conta_google_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pode_visualizar_agendas_compartilhadas',
            field=models.BooleanField(default=False, verbose_name='Pode visualizar agendas compartilhadas?'),
        ),
    ]
