# Generated by Django 5.2.3 on 2025-08-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_perfilusuario_pode_visualizar_agendas_compartilhadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipe',
            name='nome_de_guerra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de Guerra / Apelido'),
        ),
    ]
