# Generated by Django 5.2.3 on 2025-08-01 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_municipe_nome_de_guerra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título/Assunto da Reserva')),
                ('data_inicio', models.DateTimeField(verbose_name='Início da Reserva')),
                ('data_fim', models.DateTimeField(verbose_name='Fim da Reserva')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='atendimentos.espaco')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva de Espaço',
                'verbose_name_plural': 'Reservas de Espaços',
                'ordering': ['data_inicio'],
            },
        ),
    ]
