# Generated by Django 5.2.3 on 2025-08-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_reservaespaco'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaespaco',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_solicitadas', to='atendimentos.municipe'),
        ),
    ]
