# Generated by Django 5.2.3 on 2025-08-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_reservaespaco_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipe',
            name='email',
        ),
        migrations.AddField(
            model_name='municipe',
            name='emails',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Emails'),
        ),
    ]
