# Generated by Django 5.2.3 on 2025-08-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0007_remove_municipe_email_municipe_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='contas',
            field=models.ManyToManyField(related_name='espacos', to='atendimentos.conta', verbose_name='Contas com Acesso'),
        ),
    ]
