# Generated by Django 5.2.3 on 2025-08-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0008_espaco_contas'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='brasao_instituicao',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Brasão da Instituição (para relatórios)'),
        ),
        migrations.AddField(
            model_name='conta',
            name='logo_conta',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Conta/Secretaria (opcional)'),
        ),
        migrations.AddField(
            model_name='conta',
            name='nome_instituicao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Instituição (Ex: Prefeitura de Mogi das Cruzes)'),
        ),
    ]
