# Generated by Django 5.2.3 on 2025-08-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_conta_brasao_instituicao_conta_logo_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipe',
            name='tratamento',
            field=models.CharField(blank=True, help_text='Ex: Senhor, Senhora, Dr., Dra., Vossa Excelência', max_length=50, null=True, verbose_name='Pronome de Tratamento'),
        ),
    ]
