# Generated by Django 5.2.3 on 2025-09-09 17:00

import atendimentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0010_municipe_tratamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Lembrete')),
                ('conteudo', models.TextField(verbose_name='Conteúdo Detalhado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lembretes', to='atendimentos.conta', verbose_name='Conta do Lembrete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lembretes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
                'ordering': ['-data_criacao'],
            },
            bases=(atendimentos.models.UppercaseFieldsMixin, models.Model),
        ),
    ]
