# Generated by Django 5.2.3 on 2025-09-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0011_lembrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='nome_sigla',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla da Conta/Gabinete'),
        ),
        migrations.AddField(
            model_name='conta',
            name='nome_titular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Gestor Titular'),
        ),
    ]
