# Generated by Django 5.2.3 on 2025-09-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0012_conta_nome_sigla_conta_nome_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='nome_sigla',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Sigla da Conta/Gabinete'),
        ),
    ]
