# Generated by Django 5.2.3 on 2025-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0013_alter_conta_nome_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='ano_corrente_oficio',
            field=models.IntegerField(default=2025, verbose_name='Ano de Controle dos Ofícios'),
        ),
        migrations.AddField(
            model_name='conta',
            name='ultimo_numero_oficio',
            field=models.IntegerField(default=0, help_text='Controla a sequência numérica dos ofícios gerados para esta conta.', verbose_name='Último Nº de Ofício Usado'),
        ),
    ]
