# Generated by Django 5.2.3 on 2025-09-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0014_conta_ano_corrente_oficio_conta_ultimo_numero_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipe',
            name='dados_etiqueta',
            field=models.TextField(blank=True, help_text='Formato livre para a impressão de etiquetas. Ex: A/C Dr. Fulano de Tal e Família.', null=True, verbose_name='Texto para Etiqueta'),
        ),
    ]
