# Generated by Django 5.2.3 on 2025-09-17 13:42

import atendimentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0015_municipe_dados_etiqueta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TramitacaoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.TextField(verbose_name='Despacho / Nota de Progresso')),
                ('data_tramitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='atendimentos.solicitacaoagenda', verbose_name='Solicitação de Agenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Tramitação de Agenda',
                'verbose_name_plural': 'Tramitações de Agenda',
                'ordering': ['-data_tramitacao'],
            },
            bases=(atendimentos.models.UppercaseFieldsMixin, models.Model),
        ),
    ]
