# Generated by Django 5.2.3 on 2025-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0016_tramitacaoagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoagenda',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_ANALISE', 'Em Análise'), ('AGENDADO', 'Agendado'), ('NEGADO', 'Negado'), ('CANCELADO', 'Cancelado'), ('REAGENDAR', 'Reagendar')], default='SOLICITADO', max_length=20, verbose_name='Status'),
        ),
    ]
