# Generated by Django 5.2.3 on 2025-10-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0017_alter_solicitacaoagenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaespaco',
            name='grupo_recorrencia',
            field=models.UUIDField(blank=True, editable=False, help_text='Agrupa eventos recorrentes.', null=True),
        ),
    ]
