# Generated by Django 5.2.3 on 2025-10-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0018_reservaespaco_grupo_recorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoagenda',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_ANALISE', 'Em Análise'), ('AGENDADO', 'Agendado'), ('NEGADO', 'Negado'), ('CANCELADO', 'Cancelado'), ('REAGENDAR', 'Reagendar'), ('ENCAMINHADO', 'Encaminhado')], default='SOLICITADO', max_length=20, verbose_name='Status'),
        ),
    ]
