# Generated by Django 5.2.3 on 2025-12-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0020_alter_solicitacaoagenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='etiqueta_remetente',
            field=models.TextField(blank=True, help_text='Texto completo que aparecerá no canto do envelope. Use Enter para quebrar linhas.', null=True, verbose_name='Etiqueta do Remetente'),
        ),
    ]
