# Generated by Django 5.2.3 on 2026-01-12 19:46

import atendimentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0021_conta_etiqueta_remetente'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipe',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=atendimentos.models.caminho_foto_municipe, verbose_name='Foto de Perfil'),
        ),
    ]
