# Generated by Django 5.2.3 on 2026-01-12 20:40

import atendimentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0022_municipe_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCompromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Assunto / Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Detalhes / Pauta')),
                ('data_inicio', models.DateTimeField(verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('local', models.CharField(default='Gabinete', max_length=200, verbose_name='Local')),
                ('tipo', models.CharField(choices=[('REUNIAO_INTERNA', 'Reunião Interna'), ('ATENDIMENTO_GABINETE', 'Atendimento no Gabinete'), ('EVENTO_EXTERNO', 'Evento Externo'), ('VISITA_TECNICA', 'Visita Técnica'), ('CERIMONIAL', 'Cerimonial / Solenidade'), ('ALMOCO_JANTAR', 'Almoço / Jantar Oficial')], default='ATENDIMENTO_GABINETE', max_length=30)),
                ('situacao', models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('ADIADO', 'Adiado')], default='AGENDADO', max_length=20)),
                ('confidencial', models.BooleanField(default=False, help_text='Se marcado, oculta detalhes para usuários básicos, mostrando apenas horário ocupado.', verbose_name='Agenda Reservada')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_institucional', to='atendimentos.conta', verbose_name='Gabinete/Conta')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compromisso Institucional',
                'verbose_name_plural': 'Agenda Institucional',
                'ordering': ['-data_inicio'],
            },
            bases=(atendimentos.models.UppercaseFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AgendaConvidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, help_text='Ex: Entrar pelos fundos, liberar carro, etc.', max_length=100, null=True, verbose_name='Observação para Recepção')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Presença Confirmada?')),
                ('chegou', models.BooleanField(default=False, verbose_name='Realizou Check-in')),
                ('horario_chegada', models.DateTimeField(blank=True, null=True)),
                ('compromisso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to='atendimentos.agendacompromisso')),
                ('municipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_participantes', to='atendimentos.municipe')),
            ],
            options={
                'verbose_name': 'Convidado da Agenda',
                'verbose_name_plural': 'Convidados da Agenda',
            },
        ),
    ]
