# Generated by Django 5.2.3 on 2026-01-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0023_agendacompromisso_agendaconvidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='participa_escala',
            field=models.BooleanField(default=False, help_text='Se marcado, esta secretaria será cobrada no relatório de pendências.', verbose_name='Participa da Escala de Plantão?'),
        ),
    ]
