# Generated by Django 5.2.3 on 2026-01-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0024_conta_participa_escala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCompartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LEITURA', 'Apenas Visualizar'), ('ESCRITA', 'Pode Criar/Editar/Excluir')], default='LEITURA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('conta_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_agenda', to='atendimentos.conta')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_compartilhadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compartilhamento de Agenda',
                'verbose_name_plural': 'Compartilhamentos de Agenda',
                'unique_together': {('conta_alvo', 'usuario')},
            },
        ),
    ]
