# Generated by Django 5.2.3 on 2026-01-27 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0025_agendacompartilhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipe',
            name='categoria',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='atendimentos.categoriacontato', verbose_name='Categoria do Contato'),
            preserve_default=False,
        ),
    ]
