# Generated by Django 5.2.11 on 2026-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0036_atendimento_ia_fields_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipe',
            name='auditoria_ia_data',
            field=models.DateTimeField(blank=True, help_text='Data/hora da última geração do vetor IA.', null=True, verbose_name='Última atualização IA'),
        ),
        migrations.AddField(
            model_name='municipe',
            name='perfil_ia_texto',
            field=models.TextField(blank=True, help_text='Texto usado para gerar o embedding (debug).', null=True, verbose_name='Texto consolidado para vetor IA'),
        ),
        migrations.AddField(
            model_name='municipe',
            name='vetor_ia_perfil',
            field=models.JSONField(blank=True, help_text='Embedding para busca semântica do perfil.', null=True, verbose_name='Vetor IA Perfil (Embedding)'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='resumo_ia',
            field=models.TextField(blank=True, help_text='Resumo automático gerado pelo Gemini AI (legado)', null=True, verbose_name='Resumo Gerado por IA'),
        ),
        migrations.AlterField(
            model_name='municipe',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo (legado)'),
        ),
        migrations.AlterField(
            model_name='municipe',
            name='orgao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Órgão/Empresa (legado)'),
        ),
        migrations.AlterField(
            model_name='municipe',
            name='tratamento',
            field=models.CharField(blank=True, help_text='Ex: Senhor, Senhora, Dr., Dra., Vossa Excelência. Migrado para PerfilMunicipe.', max_length=50, null=True, verbose_name='Pronome de Tratamento (legado)'),
        ),
    ]
