# Generated by Django 5.2.3 on 2026-04-15 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0045_alter_automacao_alerta_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Campanha')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGENDADA', 'Agendada'), ('PROCESSANDO', 'Processando'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], db_index=True, default='RASCUNHO', max_length=20)),
                ('tipo_disparo', models.CharField(choices=[('IMEDIATO', 'Imediato'), ('AGENDADO', 'Agendado')], default='IMEDIATO', max_length=10)),
                ('data_hora_disparo', models.DateTimeField(blank=True, db_index=True, help_text='Obrigatório quando o tipo de disparo for AGENDADO.', null=True, verbose_name='Data/Hora de Disparo')),
                ('disparo_solicitado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Solicitado para fila em')),
                ('email_teste', models.EmailField(blank=True, help_text='Se preenchido, todos os envios serão direcionados para este endereço.', max_length=254, null=True, verbose_name='E-mail de teste (opcional)')),
                ('assunto_template', models.CharField(help_text='Suporta placeholders Django Template (ex.: {{ nome_completo }}).', max_length=255, verbose_name='Template de Assunto')),
                ('corpo_template', models.TextField(help_text='Suporta placeholders Django Template.', verbose_name='Template do Corpo')),
                ('arte', models.ImageField(blank=True, null=True, upload_to='campanhas/artes/', verbose_name='Imagem no corpo (inline)')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='campanhas/anexos/', verbose_name='Anexo de campanha')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ultima_execucao_em', models.DateTimeField(blank=True, null=True)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('total_enviados', models.PositiveIntegerField(default=0)),
                ('total_falhas', models.PositiveIntegerField(default=0)),
                ('categorias', models.ManyToManyField(blank=True, help_text='Se vazio, considera o mailing completo da conta.', related_name='campanhas_email', to='atendimentos.categoriacontato', verbose_name='Categorias de Contato')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_email', to='atendimentos.conta', verbose_name='Conta/Gabinete')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_email_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campanha de E-mail',
                'verbose_name_plural': 'Campanhas de E-mail',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(max_length=254, verbose_name='E-mail de destino')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanha_destinatarios', to='atendimentos.categoriacontato')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanha_destinatarios', to='atendimentos.conta', verbose_name='Conta')),
                ('municipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanha_destinatarios', to='atendimentos.municipe', verbose_name='Munícipe')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='atendimentos.campanhaemail', verbose_name='Campanha')),
            ],
            options={
                'verbose_name': 'Destinatário da Campanha',
                'verbose_name_plural': 'Destinatários da Campanha',
                'ordering': ['municipe__nome_completo'],
                'unique_together': {('campanha', 'municipe')},
            },
        ),
        migrations.CreateModel(
            name='CampanhaLogEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha')], db_index=True, max_length=10)),
                ('erro', models.TextField(blank=True, verbose_name='Detalhes do erro')),
                ('data_envio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_envio', to='atendimentos.campanhaemail', verbose_name='Campanha')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='atendimentos.campanhadestinatario', verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Log de Envio da Campanha',
                'verbose_name_plural': 'Logs de Envio da Campanha',
                'ordering': ['-data_envio'],
            },
        ),
    ]
