# Generated by Django 5.2.3 on 2026-04-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0046_campanhaemail_campanhadestinatario_campanhalogenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhalogenvio',
            name='email_real_enviado',
            field=models.EmailField(blank=True, help_text='Destinatário efetivo no SMTP (considera e-mail de teste, quando ativo).', max_length=254, null=True, verbose_name='E-mail real enviado'),
        ),
    ]
