# Generated by Django 5.2.6 on 2026-05-26 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0052_assuntos_extras_mescla_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleapitoken',
            options={'verbose_name': 'Token Google (Legado)', 'verbose_name_plural': 'Tokens Google (Legados)'},
        ),
        migrations.AddField(
            model_name='googleapitoken',
            name='data_migracao',
            field=models.DateTimeField(blank=True, help_text='Data em que foi migrado para TokenGoogleCalendar', null=True),
        ),
        migrations.AddField(
            model_name='googleapitoken',
            name='migrado',
            field=models.BooleanField(default=False, help_text='Indica se este token já foi migrado para o novo sistema'),
        ),
        migrations.AlterField(
            model_name='googleapitoken',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_token_legado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContaGoogleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome identificador (ex: 'Agenda Pública', 'Agenda Privada')", max_length=100, verbose_name='Nome da Conta Google')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada desta conta Google', verbose_name='Descrição')),
                ('email_google', models.EmailField(help_text='Email da conta Google (@gmail.com ou domínio personalizado)', max_length=254, verbose_name='Email da Conta Google')),
                ('calendar_id', models.EmailField(help_text='ID do Google Calendar (normalmente igual ao email)', max_length=254, verbose_name='ID do Google Calendar')),
                ('client_id', models.CharField(blank=True, help_text='Client ID específico (deixe vazio para usar global do .env)', max_length=255, verbose_name='Client ID OAuth')),
                ('client_secret', models.CharField(blank=True, help_text='Client Secret específico (deixe vazio para usar global do .env)', max_length=255, verbose_name='Client Secret OAuth')),
                ('usar_credenciais_globais', models.BooleanField(default=True, help_text='Se marcado, usa credenciais do arquivo .env (GOOGLE_CLIENT_ID/SECRET)', verbose_name='Usar Credenciais Globais')),
                ('ativa', models.BooleanField(default=True, verbose_name='Conta Ativa')),
                ('eh_padrao', models.BooleanField(default=False, help_text='Conta Google padrão para esta Conta/Gabinete', verbose_name='É Conta Padrão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_google', to='atendimentos.conta', verbose_name='Gabinete/Conta')),
            ],
            options={
                'verbose_name': 'Conta Google Calendar',
                'verbose_name_plural': 'Contas Google Calendar',
                'ordering': ['conta__nome', 'nome'],
                'unique_together': {('conta', 'email_google'), ('conta', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='TokenGoogleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('expires_at', models.DateTimeField(verbose_name='Data de Expiração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ultima_renovacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Renovação do Token')),
                ('conta_google', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.contagooglecalendar', verbose_name='Conta Google Calendar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token Google Calendar',
                'verbose_name_plural': 'Tokens Google Calendar',
                'ordering': ['-data_atualizacao'],
                'unique_together': {('usuario', 'conta_google')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioContaGooglePermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_visualizar', models.BooleanField(default=True, help_text='Pode ver eventos desta agenda no sistema', verbose_name='Pode Visualizar')),
                ('pode_criar', models.BooleanField(default=False, help_text='Pode criar novos eventos nesta agenda', verbose_name='Pode Criar Eventos')),
                ('pode_editar', models.BooleanField(default=False, help_text='Pode editar eventos existentes desta agenda', verbose_name='Pode Editar Eventos')),
                ('pode_excluir', models.BooleanField(default=False, help_text='Pode excluir eventos desta agenda', verbose_name='Pode Excluir Eventos')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('conta_google', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_usuarios', to='atendimentos.contagooglecalendar', verbose_name='Conta Google Calendar')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissoes_google_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_google', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão Google Calendar',
                'verbose_name_plural': 'Permissões Google Calendar',
                'ordering': ['conta_google__conta__nome', 'conta_google__nome', 'usuario__username'],
                'unique_together': {('usuario', 'conta_google')},
            },
        ),
    ]
