# Generated by Django 5.2.3 on 2026-06-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0053_multiplas_contas_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoagenda',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_ANALISE', 'Em Análise'), ('AGENDADO', 'Agendado'), ('AGENDAR', 'Agendar'), ('NEGADO', 'Negado'), ('CANCELADO', 'Cancelado'), ('REAGENDAR', 'Reagendar'), ('ENCAMINHADO', 'Encaminhado'), ('CONCLUIDO', 'Concluido')], default='SOLICITADO', max_length=20, verbose_name='Status'),
        ),
    ]
