# Generated by Django 5.2.3 on 2026-06-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0054_alter_solicitacaoagenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdeatividade',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_crm', to='atendimentos.conta', verbose_name='Conta/Gabinete'),
        ),
        migrations.AddField(
            model_name='logdeatividade',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload (diff resumido)'),
        ),
        migrations.AlterField(
            model_name='logdeatividade',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação de Atendimento'), ('EDICAO', 'Edição de Atendimento'), ('DELECAO', 'Deleção de Atendimento'), ('TRAMITACAO', 'Nova Tramitação'), ('EDICAO_TRAMITACAO', 'Edição de Tramitação'), ('DELECAO_TRAMITACAO', 'Deleção de Tramitação'), ('MUNICIPE_CRIACAO', 'Criação de Munícipe'), ('MUNICIPE_EDICAO', 'Edição de Munícipe'), ('MUNICIPE_DELECAO', 'Deleção de Munícipe'), ('PERFIL_CRIACAO', 'Criação de Perfil do Munícipe'), ('PERFIL_EDICAO', 'Edição de Perfil do Munícipe'), ('PERFIL_DELECAO', 'Deleção de Perfil do Munícipe'), ('CATEGORIA_CRIACAO', 'Criação de Categoria de Contato'), ('CATEGORIA_EDICAO', 'Edição de Categoria de Contato'), ('CATEGORIA_DESATIVACAO', 'Desativação de Categoria de Contato'), ('MESCLAGEM', 'Mesclagem de Duplicatas')], max_length=30, verbose_name='Ação Realizada'),
        ),
    ]
