# Generated by Django 5.2.3 on 2026-06-12 19:51

import django.db.models.deletion
from django.db import migrations, models


def backfill_prazos_sla(apps, schema_editor):
    Atendimento = apps.get_model('atendimentos', 'Atendimento')
    from atendimentos.services.sla_atendimento import garantir_prazos_sla

    for atendimento in Atendimento.objects.filter(prazo_conclusao__isnull=True).iterator(chunk_size=500):
        garantir_prazos_sla(atendimento, force=True)


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0055_log_crm_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='prazo_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo de conclusão (SLA)'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='prazo_resposta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo de resposta (SLA)'),
        ),
        migrations.CreateModel(
            name='SlaAtendimentoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_resposta', models.PositiveSmallIntegerField(default=3, verbose_name='Dias úteis para resposta')),
                ('dias_conclusao', models.PositiveSmallIntegerField(default=10, verbose_name='Dias úteis para conclusão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('assunto', models.ForeignKey(blank=True, help_text='Vazio = regra padrão do gabinete.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slas_config', to='atendimentos.assuntoatendimento', verbose_name='Assunto')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas_atendimento', to='atendimentos.conta', verbose_name='Conta/Gabinete')),
            ],
            options={
                'verbose_name': 'Configuração SLA de Atendimento',
                'verbose_name_plural': 'Configurações SLA de Atendimento',
                'ordering': ['conta', 'assunto'],
                'constraints': [models.UniqueConstraint(fields=('conta', 'assunto'), name='uniq_sla_conta_assunto')],
            },
        ),
        migrations.RunPython(backfill_prazos_sla, migrations.RunPython.noop),
    ]
