# Generated by Django 5.2.6 on 2026-06-15 11:48

from django.db import migrations, models


def criar_grupo_operador_crm(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Operador CRM')


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0056_sla_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='categorias_contato',
            field=models.ManyToManyField(blank=True, help_text='Escopo de categorias para usuários do grupo Operador CRM.', related_name='operadores_crm', to='atendimentos.categoriacontato', verbose_name='Categorias de contato (Operador CRM)'),
        ),
        migrations.RunPython(criar_grupo_operador_crm, migrations.RunPython.noop),
    ]
