# Generated by Django 5.2.3 on 2026-01-19 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0024_conta_participa_escala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_limite_preenchimento', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Período de Escala',
                'verbose_name_plural': 'Escalas - Períodos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EscalaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_plantao', models.CharField(max_length=30, verbose_name='Telefone Ativo no Plantão')),
                ('cargo_funcao_plantao', models.CharField(blank=True, help_text='Ex: Motorista, Técnico, Coordenador', max_length=100, verbose_name='Função no Plantão')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_registradas', to='atendimentos.conta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='escalas.escalaperiodo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas_realizadas', to='atendimentos.municipe')),
            ],
            options={
                'verbose_name': 'Registro de Plantonista',
                'verbose_name_plural': 'Escalas - Registros',
            },
        ),
    ]
