# Generated by Django 5.2.3 on 2026-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaregistro',
            name='cargo_funcao_plantao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Função no Plantão'),
        ),
    ]
