# Generated by Django 5.2.3 on 2026-01-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0002_alter_escalaregistro_cargo_funcao_plantao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, help_text='Ex: CPA/M-12', max_length=150, null=True)),
                ('ordem', models.IntegerField(default=0, help_text='Menor número aparece primeiro')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contato de Emergência',
                'verbose_name_plural': 'Contatos de Emergência',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
