"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from decouple import config
from dj_database_url import parse as dburl
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar variáveis do .env usando python-dotenv diretamente
env_path = BASE_DIR / '.env'
if not env_path.exists():
    import sys
    print("=" * 80)
    print("ERRO CRÍTICO: Arquivo .env não encontrado!")
    print(f"Esperado em: {env_path}")
    print("Crie o arquivo .env baseado no .env.example e configure todas as variáveis obrigatórias.")
    print("=" * 80)
    sys.exit(1)

load_dotenv(env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY DEVE estar no .env - SEM FALLBACK, SEM VALOR PADRÃO
SECRET_KEY = os.getenv('SECRET_KEY')

# Validação crítica: SECRET_KEY é obrigatória e não pode estar vazia
if not SECRET_KEY or not SECRET_KEY.strip():
    import sys
    print("=" * 80)
    print("ERRO CRÍTICO: SECRET_KEY não encontrada ou vazia no arquivo .env!")
    print("Configure SECRET_KEY no arquivo .env antes de executar o projeto.")
    print("Gere uma nova chave com: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'")
    print("=" * 80)
    sys.exit(1)

# Remover espaços em branco e aspas extras da SECRET_KEY
SECRET_KEY = SECRET_KEY.strip().strip('"').strip("'")

# Validação adicional: SECRET_KEY não pode ser o valor padrão inseguro conhecido
SECRET_KEY_INSECURE_DEFAULTS = [
    'django-insecure--7hk=jn*vw$wm*sd*6t=l0tkh(k5brj)_+un79yc)e9(805k4l',
    'django-insecure-key',
    'secret-key',
    'your-secret-key-here',
    'change-me',
]

if SECRET_KEY in SECRET_KEY_INSECURE_DEFAULTS or len(SECRET_KEY) < 50:
    import sys
    print("=" * 80)
    print("ERRO CRÍTICO: SECRET_KEY está usando valor padrão inseguro ou muito curta!")
    print("Configure uma SECRET_KEY segura (mínimo 50 caracteres) no arquivo .env.")
    print("Gere uma nova chave com: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'")
    print("=" * 80)
    sys.exit(1)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG DEVE estar no .env - usar python-dotenv diretamente
DEBUG_STR = os.getenv('DEBUG', 'False').strip().strip('"').strip("'")
if DEBUG_STR.lower() in ('true', '1', 'yes', 'on'):
    DEBUG = True
elif DEBUG_STR.lower() in ('false', '0', 'no', 'off', ''):
    DEBUG = False
else:
    import sys
    print("=" * 80)
    print(f"ERRO: Valor inválido para DEBUG no .env: '{DEBUG_STR}'")
    print("Use 'True' ou 'False' (string) no arquivo .env")
    print("=" * 80)
    sys.exit(1)

# Validação adicional: DEBUG não pode ser True em produção
if DEBUG:
    allowed_hosts_str = os.getenv('ALLOWED_HOSTS', '')
    if 'gabinete.mogidascruzes.sp.gov.br' in allowed_hosts_str or not allowed_hosts_str:
        import warnings
        warnings.warn(
            "⚠️ ATENÇÃO: DEBUG está True! Configure DEBUG=False no arquivo .env para produção.",
            UserWarning
        )

# ALLOWED_HOSTS: Lista de hosts permitidos
ALLOWED_HOSTS_STR = config('ALLOWED_HOSTS', default='gabinete.mogidascruzes.sp.gov.br,192.168.10.50,localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]

SITE_URL = config('SITE_URL', default='https://gabinete.mogidascruzes.sp.gov.br')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'import_export',
    'pgvector',
    'atendimentos',
    'eventos',
    'oficios',
    'etiquetas',
    'escalas',
    'core',
]

MIDDLEWARE = [
    'atendimentos.request_middleware.RequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'eventos', 'templates'),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuração do banco de dados via variáveis de ambiente
# Fallback para SQLite apenas em desenvolvimento local
default_dburl = 'sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3')

# Tenta usar configuração do .env, senão usa valores padrão
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.mysql')
DB_NAME = config('DB_NAME', default='gabinete_db')
DB_USER = config('DB_USER', default='gabinete_user')
DB_PASSWORD = config('DB_PASSWORD', default='')  # OBRIGATÓRIO em produção!
DB_HOST = config('DB_HOST', default='localhost')
DB_PORT = config('DB_PORT', default='3306')

# Validação: Senha do banco não pode estar vazia em produção
if not DB_PASSWORD and not DEBUG:
    raise ValueError(
        "❌ ERRO CRÍTICO: DB_PASSWORD não configurado! "
        "Configure DB_PASSWORD no arquivo .env antes de fazer deploy."
    )

# Configuração do banco: OPTIONS com init_command só para MySQL (SQLite não entende SET)
if DB_ENGINE == 'django.db.backends.sqlite3':
    _default_db = {
        'ENGINE': DB_ENGINE,
        'NAME': str(BASE_DIR / DB_NAME) if DB_NAME and not os.path.isabs(DB_NAME) else (DB_NAME or str(BASE_DIR / 'db.sqlite3')),
    }
else:
    _default_db = {
        'ENGINE': DB_ENGINE,
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
    if DB_ENGINE == 'django.db.backends.mysql':
        _default_db['OPTIONS'] = {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'; SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci",
        }

DATABASES = {'default': _default_db}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/siga_uploads/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF Trusted Origins: Domínios confiáveis para requisições CSRF (inclui localhost para dev)
CSRF_TRUSTED_ORIGINS_STR = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://gabinete.mogidascruzes.sp.gov.br,http://localhost:5173,http://127.0.0.1:5173'
)
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_STR.split(',') if origin.strip()]

# CORS: permitir frontend em localhost (dev) e produção
CORS_ALLOWED_ORIGINS_STR = config(
    'CORS_ALLOWED_ORIGINS',
    default='https://gabinete.mogidascruzes.sp.gov.br,http://localhost:5173,http://127.0.0.1:5173'
)
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_STR.split(',') if origin.strip()]
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# --- CONFIGURAÇÃO DE E-MAIL SMTP (MAILGRID - TI) ---
# Em desenvolvimento, pode usar console backend para ver e-mails no terminal
# Descomente a linha abaixo para desenvolvimento local:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Em produção, use SMTP backend (padrão)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='cloud77.mailgrid.net.br')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('SMTP_USER', default='')
EMAIL_HOST_PASSWORD = config('SMTP_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='comunicacao.gabinete@mogidascruzes.sp.gov.br')

# --- CONFIGURAÇÃO DO TEMPO DOS TOKENS DE ACESSO ---
SIMPLE_JWT = {
    # Duração do crachá do dia-a-dia (curto)
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),

    # Duração do crachá mestre de renovação (longo)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7), # <-- AUMENTAMOS PARA 7 DIAS

    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=15),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    # Garante que nosso gerador de token customizado seja usado
    "TOKEN_OBTAIN_SERIALIZER": "atendimentos.serializers.MyTokenObtainPairSerializer",
}

# --- CREDENCIAIS DO GOOGLE ---
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')


# --- CONFIGURAÇÃO DE LOGGING EM ARQUIVO ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/debug.log'), # Salvará em /var/www/gabinete/siga-gabinete/logs/debug.log
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Garante que a pasta de logs exista
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

SITE_ID = 1  # <-- 2. ADICIONE ESTA LINHA

# --- CONFIGURAÇÃO DO CELERY ---
# URL do Broker (gerente da fila). 'redis://localhost:6379/0' é o padrão.
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
# Onde o Celery armazena os resultados das tarefas.
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
# Formato do conteúdo aceito.
CELERY_ACCEPT_CONTENT = ['json']
# Serializador das tarefas.
CELERY_TASK_SERIALIZER = 'json'
# Serializador dos resultados.
CELERY_RESULT_SERIALIZER = 'json'

# --- CONFIGURAÇÕES DA API SINAPSE ---
SINAPSE_API_BASE_URL = config('SINAPSE_API_BASE_URL', default='https://api.mogidascruzes.sp.gov.br/api')
SINAPSE_API_TOKEN = config('SINAPSE_API_TOKEN', default='')
SINAPSE_API_TIMEOUT = config('SINAPSE_API_TIMEOUT', default=10, cast=int)

# ============================================
# CONFIGURAÇÕES DE SEGURANÇA
# ============================================

# Header para detectar HTTPS quando atrás de proxy reverso (nginx, etc)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Redireciona HTTP para HTTPS (True em produção)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)

# Cookies de sessão apenas via HTTPS (True em produção)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)

# Cookies CSRF apenas via HTTPS (True em produção)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)

# Proteção contra clickjacking
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy (recomendado para produção)
# Descomente e configure conforme necessário:
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_HSTS_SECONDS = 31536000  # 1 ano
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True