# Generated by Django 5.2.3 on 2025-09-15 19:36

import atendimentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Pimaco 6180 (10 por folha)', max_length=100, unique=True, verbose_name='Nome do Modelo')),
                ('descricao', models.TextField(blank=True, help_text='Detalhes sobre o uso ou tipo de papel deste modelo.', null=True, verbose_name='Descrição')),
                ('template_html', models.TextField(help_text='Use placeholders como {{ nome_completo }}, {{ tratamento }}, {{ endereco.logradouro }}, etc.', verbose_name='Código HTML do Template')),
            ],
            options={
                'verbose_name': 'Modelo de Etiqueta',
                'verbose_name_plural': 'Modelos de Etiqueta',
                'ordering': ['nome'],
            },
            bases=(atendimentos.models.UppercaseFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeracaoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contatos_selecionados', models.JSONField(verbose_name='Dados dos Contatos para Impressão')),
                ('posicao_inicial', models.PositiveIntegerField(default=1, help_text='O número da etiqueta na folha onde a impressão deve começar.', verbose_name='Posição de Início na Folha')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Geração')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_geradas', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etiquetas.etiquetatemplate', verbose_name='Modelo Utilizado')),
            ],
            options={
                'verbose_name': 'Geração de Etiqueta',
                'verbose_name_plural': 'Gerações de Etiquetas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
