# Generated by Django 5.2.3 on 2025-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetatemplate',
            name='etiquetas_por_pagina',
            field=models.PositiveIntegerField(default=1, help_text='Quantos itens (etiquetas/envelopes) cabem em uma única página deste modelo.', verbose_name='Itens por Página'),
        ),
    ]
