# Generated by Django 5.2.3 on 2025-09-11 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0011_lembrete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Número do Ofício')),
                ('ano', models.PositiveIntegerField(editable=False, verbose_name='Ano')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('data_documento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Documento')),
                ('destinatario_nome', models.CharField(max_length=255, verbose_name='Nome do Destinatário')),
                ('destinatario_cargo', models.CharField(max_length=255, verbose_name='Cargo do Destinatário')),
                ('destinatario_orgao', models.CharField(max_length=255, verbose_name='Órgão/Empresa do Destinatário')),
                ('corpo', models.TextField(verbose_name='Corpo do Ofício')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oficios', to='atendimentos.conta', verbose_name='Secretaria/Gabinete')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ofício',
                'verbose_name_plural': 'Ofícios',
                'ordering': ['-ano', '-id'],
            },
        ),
    ]
