# Generated by Django 5.2.3 on 2025-09-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficio',
            options={'ordering': ['-ano', '-id'], 'permissions': [('pode_gerenciar_oficios', 'Pode gerenciar o módulo de Ofícios')], 'verbose_name': 'Ofício', 'verbose_name_plural': 'Ofícios'},
        ),
    ]
