# Generated by Django 5.2.3 on 2025-09-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0002_alter_oficio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='destinatario_tratamento',
            field=models.CharField(blank=True, help_text='Ex: Prezado Senhor, Vossa Excelência, A quem possa interessar', max_length=100, null=True, verbose_name='Forma de Tratamento'),
        ),
    ]
