# Generated by Django 5.2.3 on 2026-01-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0003_oficio_destinatario_tratamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='destinatario_cargo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo do Destinatário'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='destinatario_orgao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão/Empresa do Destinatário'),
        ),
    ]
